server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: frozen-seafood-traceability-system
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: ${traceability.datasource.driver-class-name}
    url: jdbc:mysql://${traceability.datasource.host}:${traceability.datasource.port}/${traceability.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${traceability.datasource.username}
    password: ${traceability.datasource.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: false

logging:
  level:
    com:
      example:
        frozen_seafood_traceability_system:
          mapper: debug
          service: info
          controller: info
